# Generated by Django 5.2.11 on 2026-02-03 23:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (unique per user)', max_length=100)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for UI display', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code (e.g., #6366f1)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key for security', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Note title', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Note content (max 100,000 characters)', validators=[django.core.validators.MaxLengthValidator(100000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp (used for sorting recent notes)')),
                ('category', models.ForeignKey(blank=True, help_text='Category this note belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.category')),
                ('user', models.ForeignKey(help_text='Owner of this note', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user'], name='idx_category_user'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'name'], name='idx_category_user_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user'], name='idx_note_user'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-updated_at'], name='idx_note_user_updated'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['category'], name='idx_note_category'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['title'], name='idx_note_title'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-updated_at'], name='idx_note_updated'),
        ),
    ]
