# Generated by Django 5.2.11 on 2026-02-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = []
